openapi: 3.0.1
info:
  title: demo-store
  description: Mock store to demo implementation of Sessions Payment Links, Components and Legacy Payment Links
  x-cortex-git:
    github:
      repository: xendit/demo-store
  x-cortex-tag: demo-store
  x-cortex-dependency: []
  x-cortex-service-groups:
    - P4
    - simon.paris@xendit.co
  x-cortex-owners:
    - type: EMAIL
      email: simon.paris@xendit.co
    - type: SLACK
      name: wg-payment-interface
    - type: GROUP
      name: xendit/merchant-interfaces
    